// Generated by Wrangler on Wed Jun 26 2024 18:10:40 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	EN_WORDS: KVNamespace;
	AI: unknown;
}
